### ISSUE TITLE
missing openj9-0.40.0 tag?

### ISSUE THREAD

**Issue by chenrui333** [ibmruntimes/openj9-openjdk-jdk20#72]
👋 not sure if there was a tag missing for [openj9 0.40.0 release](https://github.com/eclipse-openj9/openj9/releases/tag/openj9-0.40.0), thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/139104

**Comment by pshipton** [comment]
True, I haven't created the tag on any openjdk repo yet because the final Semeru builds haven't yet been delivered. The jdk20 build is mostly done but still running. I can create the tag tomorrow or early next week once the build finishes and all looks well.

**Comment by pshipton** [comment]
I've created the tag now.

**Comment by chenrui333** [comment]
thanks!!
